### ISSUE TITLE
Import hangs while importing stock_available (multi-store to single-store)

### ISSUE THREAD

**Issue by neagoegab** [ets-soft/prestashop-migrator-free-version#1]
In my case, going from multi-store 1.6 to clean single-store 1.7.4.3 the import hung while importing stock_available. The ets_pres2pres_stock_available table kept growing because the exception caused by missing id, ...(int)$object->id ..., line 741 in DataImport.php. 

The id should be unset before add(), in lines 710 nad 703? If yes, please make a copy and restore it after add.

Best regards,
Gabriel

**Comment by ets-soft** [comment]
hi version 1.0.7 is just available. Yon can try this version. the problem should has been fixed

Cheers!

**Comment by neagoegab** [comment]
Thank you!
